### ISSUE TITLE
EPIC: Website MVP

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#100]
The landing page for https://acre.fi.

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/26
- [ ] https://github.com/thesis/acre/issues/155
- [ ] https://github.com/thesis/acre/issues/156
```
