### ISSUE TITLE
Implement Staking Flow in Ledger Live dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#107]
Implement staking flow in the Ledger Live dApp.

Figma: https://www.figma.com/file/OUdSfHsmgV8EJpWxAzXjl5/Design-Tasks?type=design&node-id=2502-28361&mode=design&t=oKUjJrxzpi9fHopO-4

---

* User sends Bitcoin transfer
* User signs mint and stake message with Ethereum account
* dApp passes the deposit data to a bot that will handle Ethereum transactions

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/95
- [ ] https://github.com/thesis/acre/issues/96
- [ ] https://github.com/thesis/acre/issues/97
- [ ] https://github.com/thesis/acre/issues/134
- [ ] https://github.com/thesis/acre/issues/136
- [x] Submit Ethereum message signature and deposit data
```
