### ISSUE TITLE
Implement Unstaking Flow in Ledger Live dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#112]
Implement unstaking flow in the Ledger Live dApp.

Figma: https://www.figma.com/file/OUdSfHsmgV8EJpWxAzXjl5/Design-Tasks?type=design&node-id=3380-25275&mode=design&t=1vG9C2eujbt5Q5tk-4

---

* User signs unstake message with Ethereum account
* dApp passes the data to a bot that will handle Ethereum transactions

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/pull/249
- [ ] https://github.com/thesis/acre/issues/127
- [ ] https://github.com/thesis/acre/pull/251
```
