### ISSUE TITLE
EPIC: Subgraph

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#114]
Implement [Subgraph](https://thegraph.com/) to expose data for the dApp.

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/263
- [ ] https://github.com/thesis/acre/issues/269
- [ ] https://github.com/thesis/acre/issues/346
- [ ] https://github.com/thesis/acre/issues/347
- [ ] https://github.com/thesis/acre/issues/267
- [ ] https://github.com/thesis/acre/issues/276
- [ ] https://github.com/thesis/acre/issues/268
- [ ] https://github.com/thesis/acre/issues/270
- [ ] https://github.com/thesis/acre/issues/356
- [ ] https://github.com/thesis/acre/issues/430
- [ ] https://github.com/thesis/acre/issues/561
```
