### ISSUE TITLE
Implement activity details in Ledger Live dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#116]
Notifications Bar
![image](https://github.com/thesis/acre/assets/10741774/1b9a5dbb-56f4-444b-9ad4-a95ed1fbd920)

Activity Details Page
![image](https://github.com/thesis/acre/assets/10741774/b7f7d6e0-a7b1-4b79-8dcc-4f36d5a91624)

```[tasklist]
### Tasks
- [ ] Notifications bar on the main page
- [ ] Subpage to show the current status of actions
- [ ] Actions state transitions
```
