### ISSUE TITLE
Implement performance stats view in Ledger Live dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#117]
- Protocol Stats (when no stake)
![image](https://github.com/thesis/acre/assets/10741774/a18c3f3c-9f50-410e-82ec-37c35365a0de)

- Staker's Stats (when the user has a stake)
![image](https://github.com/thesis/acre/assets/10741774/ec2f242c-9cda-4f86-b12b-d44fa297e5f2)

This task may require the implementation of computation in Subgraph and/or SDK.

Depends on https://github.com/thesis/acre/issues/114.

⚠️ Dune analytics link is out of the scope of this task.

```[tasklist]
### Tasks
- [ ] Create view component: https://github.com/thesis/acre/pull/274
- [ ] Compute Total Value Locked
- [ ] Compute 7-day avg APY
- [ ] Compute 90-day avg APY
- [ ] Compute Total Earned Yield
- [ ] Compute 7-day yield
- [ ] Compute 30-day yield
- [ ] Show stats for users without a stake
- [ ] Show stats for users with a stake
```
