### ISSUE TITLE
Implement performance graph in Ledger Live dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#118]
- Protocol Stats (when no stake)
![image](https://github.com/thesis/acre/assets/10741774/14d01796-fa30-4f93-855f-55bf01eaf626)

- Staker's Stats (when the user has a stake)
![image](https://github.com/thesis/acre/assets/10741774/bf277403-5c2c-4391-8ebb-b13c1b8e7a19)

This task may require the implementation of computation in Subgraph and/or SDK.

```[tasklist]
### Tasks
- [ ] Choose a library
- [ ] Expose data in Subgraph
- [ ] Show protocol performance
- [ ] Show staker's earnings
- [ ] Switch between protocol and staker's stats
```
