### ISSUE TITLE
Continue aborted staking flow in Ledger Live dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#119]
The user should be able to continue a staking flow that has been aborted for whatever reason (user aborts, closes the dApp, connection failures).

As part of this task, we must investigate how tBTC minting in the Threshold Dashboard handles the flow recovery.

```[tasklist]
### Tasks
- [ ] Determine risks and recovery process for staking flow (https://discord.com/channels/1079490158639976609/1196399370166341743)
- [ ] Determine risks and recovery process for unstaking flow
- [ ] Save data in local storage
- [ ] Load data from local storage to continue flow
- [ ] Track aborted flows in UI
- [ ] Expose JSON with deposit data so the user can download it
- [ ] Push deposit data to Sentry
```
