### ISSUE TITLE
Show values in USD in Ledger Live dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#121]
Some of the values should be displayed in both BTC and USD.

Depends on: https://github.com/thesis/acre/issues/236

```[tasklist]
### Tasks
- [x] Determine price feed (e.g. Coingecko)
- [x] Store the price
- [x] Refresh the price on dApp load
- [x] Add USD values where required by the design
```
