### ISSUE TITLE
EPIC: Staking

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#146]
```[tasklist]
### Design
- [ ] https://github.com/thesis/acre/issues/22
```

```[tasklist]
### Contracts
- [ ] https://github.com/thesis/acre/issues/25
- [ ] https://github.com/thesis/acre/pull/52
- [ ] https://github.com/thesis/acre/pull/64
- [ ] https://github.com/thesis/acre/pull/58
- [ ] https://github.com/thesis/acre/issues/59
- [ ] https://github.com/thesis/acre/issues/144
- [ ] https://github.com/thesis/acre/issues/60
- [ ] https://github.com/thesis/acre/issues/318
- [ ] https://github.com/thesis/acre/pull/376
```

```[tasklist]
### SDK
- [ ] https://github.com/thesis/acre/pull/89
- [ ] https://github.com/thesis/acre/issues/147
- [ ] https://github.com/thesis/acre/issues/149
- [ ] https://github.com/thesis/acre/issues/150
- [ ] https://github.com/thesis/acre/issues/255
- [ ] https://github.com/thesis/acre/pull/285
- [ ] https://github.com/thesis/acre/issues/258
- [ ] https://github.com/thesis/acre/issues/312
```

```[tasklist]
### dApp
- [x] Connect accounts with dApp for Bitcoin and Ethereum. (https://github.com/thesis/acre/pull/36)
- [ ] https://github.com/thesis/acre/pull/70
- [ ] https://github.com/thesis/acre/pull/88
- [ ] https://github.com/thesis/acre/issues/107
- [ ] https://github.com/thesis/acre/issues/109
- [ ] https://github.com/thesis/acre/issues/110
- [ ] https://github.com/thesis/acre/issues/111
- [ ] https://github.com/thesis/acre/issues/82
- [ ] https://github.com/thesis/acre/issues/126
- [ ] https://github.com/thesis/acre/issues/202
- [ ] https://github.com/thesis/acre/issues/84
- [ ] https://github.com/thesis/acre/issues/176
- [ ] https://github.com/thesis/acre/issues/238
- [ ] https://github.com/thesis/acre/issues/239
- [ ] https://github.com/thesis/acre/issues/234
- [ ] https://github.com/thesis/acre/issues/295
- [ ] https://github.com/thesis/acre/issues/284
- [ ] https://github.com/thesis/acre/issues/265
- [ ] https://github.com/thesis/acre/issues/323
- [ ] https://github.com/thesis/acre/issues/340
```

```[tasklist]
### Bot
- [ ] https://github.com/thesis/acre/issues/167
- [ ] https://github.com/thesis/acre/issues/168
- [ ] https://github.com/thesis/acre/issues/169
```
