### ISSUE TITLE
EPIC: DeFi Integration

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#153]
```[tasklist]
### Contracts
- [ ] https://github.com/thesis/acre/issues/189
- [ ] https://github.com/thesis/acre/issues/27
- [ ] https://github.com/thesis/acre/issues/188
- [ ] https://github.com/thesis/acre/issues/288
- [ ] https://github.com/thesis/acre/issues/128
- [ ] https://github.com/thesis/acre/issues/130
- [ ] https://github.com/thesis/acre/issues/129
- [ ] https://github.com/thesis/acre/issues/299
- [ ] https://github.com/thesis/acre/issues/289
- [ ] https://github.com/thesis/acre/issues/290
- [ ] https://github.com/thesis/acre/issues/291
- [ ] https://github.com/thesis/acre/issues/292
- [ ] https://github.com/thesis/acre/issues/300
- [ ] https://github.com/thesis/acre/issues/293
- [ ] https://github.com/thesis/acre/issues/304
- [ ] https://github.com/thesis/acre/issues/306
- [ ] Implement limits for loss coverage for each strategy
```

```[tasklist]
### dApp
- [ ] https://github.com/thesis/acre/issues/117
- [ ] https://github.com/thesis/acre/issues/118
```

```[tasklist]
### Bot
- [ ] Allocate funds to Vaults
- [ ] Rebalance Vaults
```
```[tasklist]
### Tests
- [ ] https://github.com/thesis/acre/issues/279
```
