### ISSUE TITLE
EPIC: dApp post-MVP Improvements

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#154]
```[tasklist]
- [ ] https://github.com/thesis/acre/issues/331
- [ ] https://github.com/thesis/acre/issues/336
- [ ] https://github.com/thesis/acre/issues/227
- [ ] https://github.com/thesis/acre/issues/214
- [ ] https://github.com/thesis/acre/issues/206
- [ ] https://github.com/thesis/acre/issues/122
- [ ] https://github.com/thesis/acre/issues/87
- [ ] https://github.com/thesis/acre/issues/225
- [ ] https://github.com/thesis/acre/issues/113
- [ ] https://github.com/thesis/acre/issues/193
- [ ] https://github.com/thesis/acre/issues/648
- [ ] https://github.com/thesis/acre/issues/120
- [ ] https://github.com/thesis/acre/issues/230
- [ ] https://github.com/thesis/acre/issues/266
- [ ] https://github.com/thesis/acre/issues/123
- [ ] https://github.com/thesis/acre/issues/81
- [ ] https://github.com/thesis/acre/issues/101
- [ ] https://github.com/thesis/acre/issues/125
- [ ] https://github.com/thesis/acre/issues/29
- [ ] https://github.com/thesis/acre/issues/83
- [ ] https://github.com/thesis/acre/issues/178
- [ ] https://github.com/thesis/acre/issues/187
- [ ] https://github.com/thesis/acre/issues/196
- [ ] https://github.com/thesis/acre/issues/229
- [ ] https://github.com/thesis/acre/issues/252
- [ ] https://github.com/thesis/acre/issues/260
- [ ] https://github.com/thesis/acre/issues/275
- [ ] https://github.com/thesis/acre/issues/277
- [ ] https://github.com/thesis/acre/issues/301
- [ ] https://github.com/thesis/acre/issues/298
- [ ] https://github.com/thesis/acre/issues/315
- [ ] https://github.com/thesis/acre/issues/327
- [ ] https://github.com/thesis/acre/issues/383
- [ ] https://github.com/thesis/acre/issues/448
- [ ] https://github.com/thesis/acre/issues/441
```
