### ISSUE TITLE
EPIC: State and History

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#157]
```[tasklist]
### dApp
- [ ] https://github.com/thesis/acre/issues/38
- [ ] https://github.com/thesis/acre/issues/236
- [ ] https://github.com/thesis/acre/issues/116
- [ ] https://github.com/thesis/acre/issues/119
- [ ] https://github.com/thesis/acre/issues/121
- [ ] https://github.com/thesis/acre/issues/115
- [ ] https://github.com/thesis/acre/issues/237
- [ ] https://github.com/thesis/acre/issues/264
```
