### ISSUE TITLE
Make contracts upgradable

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#171]
The goal of this task is to ensure the contracts are upgradable.
A good example of an upgradable contracts is the [`Bridge` contract in tbtc-v2 repo](https://github.com/keep-network/tbtc-v2/blob/main/solidity/contracts/bridge/Bridge.sol).

- [ ] We must switch dependency from `@openzeppelin/contracts` to `@openzeppelin/contracts-upgradeable`.
- [ ] Constructors should be replaced with initializers.
- [ ] Contracts deployment scripts should be updated to use `helpers.upgrades.deployProxy`.
- [ ] We need to cover the upgrades with tests, similar to https://github.com/thesis/mezo-portal/pull/42.
- [ ] Add script to transfer ProxyAdmin ownership (https://github.com/keep-network/tbtc-v2/blob/main/solidity/deploy/26_transfer_proxy_admin_ownership.ts).

```[tasklist]
### Tasks
- [ ] Make stBTC upgradable
- [ ] Make AcreBitcoinDepositor upgradable
- [ ] Make Allocator upgradable
- [ ] Make Reserve upgradable
```
