### ISSUE TITLE
EPIC: Core Contracts Initialization

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#2]
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/pull/7
- [ ] https://github.com/thesis/acre/pull/8
- [ ] https://github.com/thesis/acre/pull/10
- [ ] https://github.com/thesis/acre/pull/13
- [ ] https://github.com/thesis/acre/pull/46
- [ ] https://github.com/thesis/acre/pull/47
- [ ] https://github.com/thesis/acre/pull/48
- [ ] https://github.com/thesis/acre/pull/49
- [ ] https://github.com/thesis/acre/pull/72
- [ ] https://github.com/thesis/acre/pull/58
- [ ] https://github.com/thesis/acre/pull/85
- [ ] https://github.com/thesis/acre/pull/12
- [ ] https://github.com/thesis/acre/pull/80
- [ ] https://github.com/thesis/acre/pull/98
- [ ] https://github.com/thesis/acre/pull/133
- [ ] https://github.com/thesis/acre/pull/131
```

----
## ⚠️ Staking-related tasks were moved to https://github.com/thesis/acre/issues/146.
----
## ⚠️ Staking-related tasks were moved to https://github.com/thesis/acre/issues/152.
----
## ⚠️ Dispatching-related tasks were moved to https://github.com/thesis/acre/issues/153.
----
