### ISSUE TITLE
EPIC: Ledger Live dApp Initialization

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#20]
The Ledger Live dApp should be a dashboard a user uses for staking with Acre.

Working copy of designs: https://www.figma.com/file/OUdSfHsmgV8EJpWxAzXjl5/Design-Tasks?type=design&node-id=2393-19656&mode=design&t=vK6UJsy8Kn3zw9CO-0

The Ledger Live dApp was initially tracked by https://github.com/threshold-network/pm/issues/25.

```[tasklist]
### Configuration
- [x] Review https://github.com/threshold-network/token-dashboard/pull/655
- [ ] https://github.com/thesis/acre/pull/17
- [ ] https://github.com/thesis/acre/pull/18
- [ ] https://github.com/thesis/acre/issues/24
- [ ] https://github.com/thesis/acre/pull/50
- [ ] https://github.com/thesis/acre/pull/19
- [ ] https://github.com/thesis/acre/pull/104
- [ ] https://github.com/thesis/acre/pull/108
- [ ] https://github.com/thesis/acre/pull/124
- [ ] https://github.com/thesis/acre/issues/140
- [ ] https://github.com/thesis/acre/issues/99
- [ ] https://github.com/thesis/acre/issues/141
- [ ] https://github.com/thesis/acre/issues/139
```

----
## ⚠️ Staking-related tasks were moved to https://github.com/thesis/acre/issues/146.
----
## ⚠️ Unstaking-related tasks were moved to https://github.com/thesis/acre/issues/152.
----
## ⚠️ History-related tasks were moved to https://github.com/thesis/acre/issues/157.
----
## ⚠️ Performace-related tasks were moved to https://github.com/thesis/acre/issues/153
----
## ⚠️ Improvements-related tasks were moved to https://github.com/thesis/acre/issues/154
----
