### ISSUE TITLE
EPIC: Website Placeholder

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#21]
The initial placeholder website for https://acre.fi.

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/pull/14
- [ ] https://github.com/thesis/acre/pull/16
- [ ] https://github.com/thesis/acre/pull/43
- [x] Design the landing page placeholder
- [x] Implement the landing page placeholder
- [ ] https://github.com/thesis/acre/pull/54
- [ ] https://github.com/thesis/acre/pull/55
- [x] Host and expose the landing page
```
