### ISSUE TITLE
EPIC: Contracts Security (pt. 2)

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#218]
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/173
- [ ] https://github.com/thesis/acre/issues/174
- [ ] https://github.com/thesis/acre/issues/175
```
