### ISSUE TITLE
Show error message to the user in staking flow

### ISSUE THREAD

**Issue by kkosiorowska** [thesis/acre#265]
Currently, in our staking flow, we do not show the user any errors when something goes wrong. Let's handle the below fail scenarios:

```[tasklist]
### Tasks
- [x] Message signing error (https://github.com/thesis/acre/pull/313)
- [x] Deposit transaction execution error (https://github.com/thesis/acre/pull/313)
- [x] Deposit address validation failed or address is invalid (https://github.com/thesis/acre/pull/313)
- [x] Deposit transaction executed correctly while further steps failed to execute the stake (https://github.com/thesis/acre/pull/325)
```
