### ISSUE TITLE
Implement Dispatcher for deposits

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#27]
Implement Router contract inspired by [ERC4626RouterBase](https://github.com/ERC4626-Alliance/ERC4626-Contracts/blob/main/src/ERC4626RouterBase.sol).

The contract will be used to route staked tBTC to the Yield Modules.
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/pull/62
- [ ] https://github.com/thesis/acre/pull/71
- [ ] Define allocations ratio for vaults
- [ ] Deposit funds based on allocations ratio
```
