### ISSUE TITLE
Global styles

### ISSUE THREAD

**Issue by kkosiorowska** [thesis/acre#29]
We should use shared components and global styles to keep consistency. This translates to the following task list:

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/pull/28
- [ ] https://github.com/thesis/acre/pull/61
- [x] Make sure that the colors are defined correctly (https://github.com/thesis/acre/pull/65)
- [x] Make sure that the typography is defined correctly (https://github.com/thesis/acre/pull/67)
- [x] Make sure that the components match those defined in the style guide
```
