### ISSUE TITLE
EPIC: Mezo Integration

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#316]
This EPIC defines a list of tasks required for Mezo Portal integration.
Acre will integrate with Mezo [Portal](https://github.com/thesis/mezo-portal/blob/186db5b1380ae88d37651b2e056221de2e9f8e2d/solidity/contracts/Portal.sol) contract to deposit staked tBTC.

```[tasklist]
### Contracts
- [ ] https://github.com/thesis/acre/issues/320
- [ ] https://github.com/thesis/acre/issues/321
- [ ] https://github.com/thesis/acre/issues/345
```

```[tasklist]
### Bots
- [ ] https://github.com/thesis/acre/issues/322
```
