### ISSUE TITLE
EPIC: Bitcoin-native experience

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#319]
Users should deposit and withdraw with a Bitcoin account in Ledger Live. To achieve that we will integrate [OrangeKit](https://github.com/thesis/orangekit) with Ledger Wallet API.

This EPIC aims to integrate Ledger Live dApp with OrangeKit and introduce a Bitcoin-only experience in the deposit and withdrawal flows.

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/351
- [ ] https://github.com/thesis/acre/issues/426
- [ ] https://github.com/thesis/acre/issues/428
- [ ] https://github.com/thesis/acre/pull/437
- [ ] https://github.com/thesis/acre/issues/464
- [ ] https://github.com/thesis/acre/issues/353
- [ ] https://github.com/thesis/acre/issues/352
```
