### ISSUE TITLE
Improve stBTC tests coverage for MezoAllocator

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#345]
We need to improve stBTC test coverage for cases where funds are routed to MezoPortal via MezoAllocator.
We should cover deposit/mint/withdraw/redeem scenarios with different combinations of funds sitting in the stBTC buffer and being routed with MezoAllocator.
We should also ensure `totalAssets` works correctly for different funds distribution scenarios.

Right now changes introduced to the stBTC contract in https://github.com/thesis/acre/pull/326 are not covered in tests.

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/pull/350
- [ ] https://github.com/thesis/acre/pull/372
- [ ] https://github.com/thesis/acre/pull/380
```
