### ISSUE TITLE
Subgraph: Deploy subgraph on Sepolia

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#346]
Deploy a public instance of subgraph for Sepolia testnet.

```[tasklist]
### Tasks
- [x] Create a wallet account for the Acre team
- [x] Deploy subgraph in the Subgraph Studio
- [x] Publish the subgraph on Arbitrum Sepolia -  test publication for free
- [ ] https://github.com/thesis/acre/pull/390
```
