### ISSUE TITLE
EPIC: Ledger Live dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#354]
This epic covers the implementation of the Ledger Live dApp.

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/355
- [ ] https://github.com/thesis/acre/issues/359
- [ ] https://github.com/thesis/acre/issues/420
- [ ] https://github.com/thesis/acre/pull/745
- [ ] https://github.com/thesis/acre/issues/51
- [ ] https://github.com/thesis/acre/issues/754
- [ ] https://github.com/thesis/acre/issues/707
- [ ] https://github.com/thesis/acre/issues/753
- [ ] https://github.com/thesis/acre/issues/759
- [ ] https://github.com/thesis/acre/issues/752
- [ ] https://github.com/thesis/acre/issues/755
- [x] Update Ledger Live wallet connector to work with Acre Ledger App
- [x] Revert workaround for session caching
- [ ] https://github.com/thesis/acre/issues/772
- [x] Display `GateModal` only for the standalone dApp
```
