### ISSUE TITLE
dApp Dashboard: Refactor layout to match new L2 design

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#396]
![image](https://github.com/thesis/acre/assets/10741774/7b49333e-8441-41a5-8aff-d37744502d7c)

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/pull/409
- [ ] https://github.com/thesis/acre/pull/378
- [ ] https://github.com/thesis/acre/pull/400
- [ ] https://github.com/thesis/acre/pull/384
- [ ] https://github.com/thesis/acre/pull/385
- [ ] https://github.com/thesis/acre/pull/407
```
