### ISSUE TITLE
dApp: Data handling for activities

### ISSUE THREAD

**Issue by kkosiorowska** [thesis/acre#424]
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/425
- [x] Interval fetch of activities
- [x] Update an activities state - (`activities`, `latestActivities`)
```
