### ISSUE TITLE
dApp: Display the transaction fee for withdrawal

### ISSUE THREAD

**Issue by kkosiorowska** [thesis/acre#447]
Currently, we do not display the fee value for withdrawal transactions to the user. What should be done:

![Screenshot 2024-06-04 at 16 13 48](https://github.com/thesis/acre/assets/23117945/01ed159c-5d4d-4233-9af8-0f51237513a9)

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/pull/495
- [ ] Fetch the necessary information from the SDK.
- [ ] Display the correct values for the fee (fee value + tooltip). Needs to be confirmed what should be displayed in the tooltip.
```
