### ISSUE TITLE
EPIC: Standalone dApp MVP

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#457]
The dApp should work as a standalone web browser application. At the first stage, it won't be embedded into Ledger Live or other wallets (although we should implement it in the way embedding the dApp in the future won't require serious refactoring).

The dApp should work with OrangeKit and wallets that are supported by it.

```[tasklist]
### General
- [ ] https://github.com/thesis/acre-bots/issues/8
- [ ] https://github.com/thesis/acre/issues/355
- [ ] https://github.com/thesis/acre/issues/463
- [ ] https://github.com/thesis/acre/issues/494
- [ ] https://github.com/thesis/acre/issues/480
- [ ] https://github.com/thesis/acre/issues/477
- [ ] https://github.com/thesis/acre/issues/362
- [ ] https://github.com/thesis/acre/issues/396
- [ ] https://github.com/thesis/acre/issues/328
- [ ] https://github.com/thesis/acre/pull/454
- [ ] https://github.com/thesis/acre/issues/433
- [ ] https://github.com/thesis/acre/issues/451
- [ ] https://github.com/thesis/acre/issues/469
- [ ] https://github.com/thesis/acre/issues/505
- [ ] https://github.com/thesis/acre/issues/503
- [ ] https://github.com/thesis/acre/issues/506
- [ ] https://github.com/thesis/acre/issues/508
- [ ] https://github.com/thesis/acre/issues/507
- [ ] https://github.com/thesis/acre/issues/561
- [ ] https://github.com/thesis/acre/issues/516
```

```[tasklist]
### Deposit
- [ ] https://github.com/thesis/acre/issues/363
- [ ] https://github.com/thesis/acre/issues/366
- [ ] https://github.com/thesis/acre/issues/394
- [ ] https://github.com/thesis/acre/issues/432
- [ ] https://github.com/thesis/acre/pull/455
- [ ] https://github.com/thesis/acre/issues/509
- [ ] https://github.com/thesis/acre/issues/504
```

```[tasklist]
### Withdraw
- [ ] https://github.com/thesis/acre/issues/395
- [ ] https://github.com/thesis/acre/issues/367
- [ ] https://github.com/thesis/acre/issues/365
- [ ] https://github.com/thesis/acre/issues/447
- [ ] https://github.com/thesis/acre/issues/476
- [ ] https://github.com/thesis/acre/issues/490
- [ ] https://github.com/thesis/acre/issues/562
```

```[tasklist]
### Gamification
- [ ] https://github.com/thesis/acre/issues/360
- [ ] https://github.com/thesis/acre/issues/361
- [ ] https://github.com/thesis/acre/issues/460
- [ ] https://github.com/thesis/acre/issues/462
- [ ] https://github.com/thesis/acre/issues/461
- [ ] https://github.com/thesis/acre/issues/531
```

```[tasklist]
### Fixes
- [ ] https://github.com/thesis/acre/issues/424
- [ ] https://github.com/thesis/acre/pull/431
- [ ] https://github.com/thesis/acre/pull/434
- [ ] https://github.com/thesis/acre/pull/436
- [ ] https://github.com/thesis/acre/pull/438
- [ ] https://github.com/thesis/acre/pull/446
- [ ] https://github.com/thesis/acre/issues/442
```

```[tasklist]
### Post-MVP
- [ ] https://github.com/thesis/acre/issues/478
- [ ] https://github.com/thesis/acre/issues/479
```

```[tasklist]
### Triage
- [ ] https://github.com/thesis/acre/issues/512
- [ ] https://github.com/thesis/acre/issues/514
- [ ] https://github.com/thesis/acre/issues/524
- [ ] https://github.com/thesis/acre/issues/525
- [ ] https://github.com/thesis/acre/issues/529
- [ ] https://github.com/thesis/acre/issues/554
- [ ] https://github.com/thesis/acre/issues/555
- [ ] https://github.com/thesis/acre/issues/557
- [ ] https://github.com/thesis/acre/issues/559
- [ ] https://github.com/thesis/acre/issues/556
- [ ] https://github.com/thesis/acre/issues/558
- [ ] https://github.com/thesis/acre/issues/560
- [ ] https://github.com/thesis/acre/issues/575
- [ ] https://github.com/thesis/acre/issues/574
- [ ] https://github.com/thesis/acre/issues/576
- [ ] https://github.com/thesis/acre/issues/579
- [ ] https://github.com/thesis/acre/issues/633
- [ ] https://github.com/thesis/acre/issues/627
- [ ] https://github.com/thesis/acre/issues/596
```
