### ISSUE TITLE
Integrate dApp with Xverse

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#565]
We want to integrate dApp with the Xverse wallet.

When the user opens the dApp from the link https://stake.acre.fi, Xverse should be available for wallet selection.

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/orangekit/pull/115
- [x] Add Xverse to wallet selection
- [x] Support Nested Segwit addresses
```

In another task, https://github.com/thesis/acre/issues/617, we will register Xverse as a partner for referrals.
