### ISSUE TITLE
Integrate tBTC minting with Acre staking

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#60]
Depends on https://github.com/keep-network/tbtc-v2/issues/749

Implement tBTC Depositor contract.

```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/tbtc-v2/pull/779
- [ ] https://github.com/thesis/acre/pull/91
- [ ] https://github.com/thesis/acre/pull/253
```
