### ISSUE TITLE
Register Xverse as referral partner

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#617]
In https://github.com/thesis/acre/issues/565, we added Xverse as a supported wallet.

When the user opens the dApp from the link https://stake.acre.fi/?partner=xverse, the dApp should skip the wallet selection modal and use the Xverse wallet by default.

Additionally, when the partner is provided as `xverse` in the URL, we should set the referral for the deposit to `21060`.

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/566
- [ ] Handle `partner` flag in the URL
- [ ] Set referral for the deposit
```
