### ISSUE TITLE
EPIC: Acre Points

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#638]
We want to introduce a points mechanism for Acre depositors.

Discord thread: [link](https://discord.com/channels/1079490158639976609/1255862957762416640)
Product Pitch: [link](https://coda.io/d/Acre_d3Vs1FswTQA/Acre-Points-Pitch_sucMz#_luLmy)
```[tasklist]
### Backend
- [x] Points calculation backend
- [x] Store points in DB
- [ ] https://github.com/thesis/acre-bots/pull/24#discussion_r1745037117
- [ ] https://github.com/thesis/acre/issues/722
- [ ] https://github.com/thesis/acre-bots/issues/34
- [ ] https://github.com/thesis/acre-bots/issues/26
- [ ] https://github.com/thesis/acre-bots/issues/33
- [ ] https://github.com/thesis/acre-bots/issues/28
- [ ] https://github.com/thesis/acre/issues/765
```
```[tasklist]
### UI
- [x] Points balance component
- [x] Points claiming
- [x] Points in Deposit/Withdraw form
- [x] Authorization with SIWW
- [ ] https://github.com/thesis/acre/pull/704
```

```[tasklist]
### Bugs
- [ ] https://github.com/thesis/acre/issues/749
- [ ] https://github.com/thesis/acre/issues/735
- [ ] https://github.com/thesis/acre/issues/736
- [ ] https://github.com/thesis/acre/issues/738
- [ ] https://github.com/thesis/acre/issues/740
- [ ] https://github.com/thesis/acre/issues/739
- [ ] https://github.com/thesis/acre/issues/737
```

```[tasklist]
### Non-blocking
- [ ] https://github.com/thesis/acre-bots/issues/27
- [ ] Store Bitcoin address along the Ethereum address in the users table
- [ ] https://github.com/thesis/acre-bots/issues/29
- [ ] https://github.com/thesis/acre/issues/728
- [ ] https://github.com/thesis/acre-bots/issues/30
- [ ] Leaderboard
- [ ] Documentation (README, JSDocs)
```
