### ISSUE TITLE
Deposit/Withdraw form improvements

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#674]
```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/611
- [ ] https://github.com/thesis/acre/issues/652
- [ ] https://github.com/thesis/acre/issues/538
- [ ] https://github.com/thesis/acre/issues/637
- [ ] https://github.com/thesis/acre/issues/629
- [ ] https://github.com/thesis/acre/issues/570
- [ ] https://github.com/thesis/acre/issues/587
- [ ] https://github.com/thesis/acre/issues/630
```
