### ISSUE TITLE
Display Mezo points in the Beehive component

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#689]
Mezo API exposes the points number earned by Acre deposits.
We should include the value in the Beehive Component.

Endpoint: https://portal.api.mezo.org/api/v1/acre
The endpoint requires Bearer Token authorization with an API Key.

Example response:
```
{"totalPoints":20568,"dailyPoints":2164}
```

⚠️ The response parameters are going to be renamed to `totalMats`, `dailyMats`.

### Designs

[Figma](https://www.figma.com/design/j2MModNsoiOYNuBBXbWiM8/Web-dApp?node-id=15948-20844&t=najkza1xAXY4oFO7-0)

![image](https://github.com/user-attachments/assets/64648f7c-a18d-4ec8-8ec0-df042f03a98a)

```[tasklist]
### Tasks
- [ ] https://github.com/thesis/acre/issues/691
- [ ] https://github.com/thesis/acre/issues/692
- [ ] https://github.com/thesis/acre/issues/693
```
