### ISSUE TITLE
dApp Redesign

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#719]
Figma: [link](https://www.figma.com/design/j2MModNsoiOYNuBBXbWiM8/Web-dApp?node-id=16848-27257&node-type=FRAME&m=dev)

```[tasklist]
### Tasks
- [ ] Change the navigation menu in the header
- [ ] Remove the Season landing page
- [ ] Change the "Connect wallet" button background
- [ ] Add Tooltip to the beehive component
- [ ] Rename Beehive to L2 Rewards
- [ ] Change behavior for the not connected user (display empty state)
```
