### ISSUE TITLE
[Analytics] PostHog integration

### ISSUE THREAD

**Issue by kpyszkowski** [thesis/acre#747]
### Objective

The objective is to track usage, learn from actual user behavior to improve the product.

Things we care about: 
* Conversion funnel: Discovery > Deposit > Return
* Drop-off rate / exit points
* Traffic origin / attribution
* User data
  * Wallet type
  * BTC balance
  * Geolocation
* Sessions: overall, count per day, per week etc.
* Session Length: The duration of time users spend on the interface in one session.
* Task Success Rate
* Error Rate
* Time on Task: The time it takes for users to complete a task. (Deposit, Withdraw)

### Solution 

The solution is to integrate PostHog:
* Purpose: Product analytics.
* Importance: Provides detailed insights into user behavior and product usage, helping to optimize the user experience and guide data-driven product development.\
* How: [PostHog JS SDK](https://posthog.com/docs/libraries/node) and [Threshold Dashboard](https://github.com/threshold-network/token-dashboard) as a reference.

_\* Based on [product pitch document](https://coda.io/d/Acre_d3Vs1FswTQA/Analytics-setup_sucOf0DQ#_lujwPTEG) and [open discussion](https://discord.com/channels/1079490158639976609/1257846488248356904)._

```[tasklist]
### Tasks
- [ ] Install and configure `posthog-js` library: configuration, feature flag
- [ ] Implement basic hooks: identify, capture, capture page view
- [ ] Attach PostHog's captures to specific user behaviors: TBA
```
