### ISSUE TITLE
Update navigation in Landing Page and dApp

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#755]
We should update the navigation bar and make it consistent across the landing page and the dApp.

Discord thread: [here](https://discord.com/channels/1079490158639976609/1291702782394372148).

```[tasklist]
### Tasks
- [x] Update navigation in the Ledger Live dApp
- [x] Update navigation in the Standalone dApp
- [x] Remove links component from the dApp
```
