### ISSUE TITLE
[dApp] Update Acre points estimation tiers

### ISSUE THREAD

**Issue by kpyszkowski** [thesis/acre#784]
As discussed during [Dev/Design sync](https://discord.com/channels/1079490158639976609/1298958469415571486/1298958473199091816) it was decided to update Acre points estimation tiers. 

```[tasklist]
### Tasks
- [x] Remove yearly tier
- [x] Present _Monthly_, _Daily_ and _Weekly_ tiers
- [x] Set _Monthly_ tier as default
```
