### ISSUE TITLE
Adjust copy on the welcome panel

### ISSUE THREAD

**Issue by michalinacienciala** [thesis/acre#859]
As discussed in https://discord.com/channels/1079490158639976609/1306530286607273995/1306543315902005281 and shown in [designs](https://www.figma.com/design/j2MModNsoiOYNuBBXbWiM8/Standalone-App-Design?node-id=18104-420&node-type=frame&t=67sDG3DQDzwykCXz-0), we need comma between these words:
![image](https://github.com/user-attachments/assets/0c3f87b8-b1c9-4dfe-ab10-dccbe3d30ee6)

Also there's an obsolete `everyone` in this sentence: `Tailored for Ledger Live everyone, it's fun and easy to use.`. The [designs](https://www.figma.com/design/Ov4M1oVlSrO4Pl7NmGOHC1/Ledger-2025?node-id=446-3006) don't have it.
<img width="863" alt="image" src="https://github.com/user-attachments/assets/063bb716-6785-4910-bafb-d0b6b6cfcf8b">

```[tasklist]
### Tasks
- [ ] Add comma between "One dashboard, endless rewards"
- [ ] Remove `everyone` from `Tailored for Ledger Live everyone`
- [ ] Change button label from `Skip` to `Next`
```
